### ISSUE TITLE
Add NVMe drive support

### ISSUE THREAD

**Issue by ProphesorIks** [lucidpetal/artix-luks-base-install#1]
First of all. Awesome script, thank you for the work.
### Description
At the moment script is hardcoded to use _device1_ and _device2_ as partition names. This is works well for sdX drives, but fails for NVMe since partititions there are labeled as  nvme0nX**p**1 nvme0nX**p**2
#### To Reproduce
Pass _nvme0n1_ as the first argument
### Tasks
- [ ] Investigate other cases where user might want to install on a device not matching /dev/sdX naming scheme
- [ ] Decide if script should  automagically to add the missing letter after detecting case or just use a flag
- [ ] Test the behaviour
- [ ] Update README accordingly
